# Use Steven Cooney's minimal docker image.
image: stevencooney/docker-slim:latest

# Since we building docker images within a docker container we need the
# docker in docker service.
services:
  - docker:dind

stages:
  - build
  - test
  - publish

# Log in to Gitlab's docker registry
before_script:
  - export COMMIT_IMAGE=$( echo $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHA | tr '[:upper:]' '[:lower:]' )
  - export TAGGED_IMAGE=$( echo $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG | tr '[:upper:]' '[:lower:]' )
  - export GITHUB_URL=https://TheYorkshireDev:${GITHUB_TOKEN}@github.com/TheYorkshireDev/docker-bootstrap.git
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Build our docker image and push to Gitlab's registry
build:
  stage: build
  script:
    - docker build --pull -t $COMMIT_IMAGE .
    - docker push $COMMIT_IMAGE

# Test our docker image and verify that the container runs and anything supposed to be installed is
test:
  stage: test
  script:
    - docker pull $COMMIT_IMAGE
    - docker run -i $COMMIT_IMAGE /bin/sh -c 'docker --version'

# If the build has a tag, then use it it release a docker image
publish:
  stage: publish
  script:
    - docker pull $COMMIT_IMAGE
    - docker tag $COMMIT_IMAGE $TAGGED_IMAGE
    - docker push $TAGGED_IMAGE
  only:
    - tags

# If the build has a tag we should update the github repo too.
github_publish:
  image: stevencooney/docker-git:latest
  stage: publish
  script:
    - echo "Release to Github."
    - git remote add github "$GITHUB_URL"
    - git push github master --follow-tags
  only:
    - tags
